### ISSUE TITLE
AWS Amplify doesn't create amplify_outputs.json file.

### ISSUE THREAD

**Issue by pedy711** [salihgueler/triv_ai#1]
Hi Salih, could you please help me out with amplify_outputs.json file and amplify.yml file? Would be great if you post your "amplify.yml" file that you used in your AWS Amplify project. I get the following error because Amplify doesn't generate the "amplify_outputs.json" file in the backend tab.

<img width="1073" alt="image" src="https://github.com/user-attachments/assets/e711b823-5a12-41f5-8aba-188145901031">

**Comment by salihgueler** [comment]
Hello @pedy711, thanks for creating this issue. `npx ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID --outputs-format dart --outputs-out-dir lib` this line from below should fix it :) 

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - npm ci --cache .npm --prefer-offline
        - npx ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID --outputs-format dart --outputs-out-dir lib
frontend:
  phases:
    preBuild:
      commands:
        - echo "Installing Flutter SDK"
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - export PATH="$PATH:$(pwd)/flutter/bin"
        - flutter config --no-analytics
        - flutter doctor
    build:
      commands:
        - echo "Installing dependencies"
        - flutter pub get
        - echo "Building Flutter web application with WASM support"
        - flutter build web
  artifacts:
    baseDirectory: build/web
    files:
      - '**/*'
  cache:
    paths:
      - flutter/.pub-cache
```
